# Generated by Django 6.0.3 on 2026-03-26 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, editable=False, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='ISBN must be 10-13 digits only.', regex='^\\d{10,13}$')])),
                ('cost_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('selling_price_local', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(max_length=255)),
                ('supplier_country', models.CharField(choices=[('US', 'US'), ('ES', 'ES'), ('VE', 'VE'), ('CO', 'CO'), ('MX', 'MX'), ('AR', 'AR')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
